#%RAML 1.0 NamedExample

value:
  p_id?: "1001"
  p_name: "Shirt"
  brand: "ABC"
  category: "Casual Shirts"
  stockStatus: "Available"
  returnable: True
  p_color: "White"
  p_size: "M"
  p_price: "999.00"