#%RAML 1.0 NamedExample

value:
-
  p_id?: "1001"
  p_name: "Shirt"
  brand: "ABC"
  category: "Casual Shirts"
  stockStatus: "Available"
  returnable: True
  p_color: "White"
  p_size: "M"
  p_price: "1999.00"
-
  p_id?: "1002"
  p_name: "T-Shirt"
  brand: "ABC"
  category: "Casual T-Shirts"
  stockStatus: "Available"
  returnable: True
  p_color: "Black"
  p_size: "M"
  p_price: "999.00"
-
  p_id?: "1003"
  p_name: "Trouser"
  brand: "XYZ"
  category: "Trousers"
  stockStatus: "Available"
  returnable: True
  p_color: "Blue"
  p_size: "M"
  p_price: "2999.00"
-
  p_id?: "1004"
  p_name: "Shirt"
  brand: "ABC"
  category: "Casual Shirts"
  stockStatus: "Available"
  returnable: True
  p_color: "Red"
  p_size: "L"
  p_price: "999.00"