#%RAML 1.0 DataType
displayName: order_details
description: This is the data type in eCom api RAML

type: object
properties:
  p_id?: string
  p_name: string
  brand: string
  category: string
  stockStatus: string
  returnable: boolean
  p_color: string
  p_size: string
  p_price: string